cart/urls.py
from django.urls import path

from .views import (
    CartListView,
    AddItemToCartView,
    RemoveItemFromCart,
    ShippingAddresses,
    charge
)

urlpatterns = [
    path('cart/', CartListView.as_view(), name='view_cart'),
    path('shipping/info/', ShippingAddresses.as_view(), name='shipping_info'),
    path('add/item/<int:pk>/',
        AddItemToCartView.as_view(), name='add_item_to_cart'),
    path('remove/item/<int:pk>/',
        RemoveItemFromCart.as_view(), name='remove_item_from_cart'),
    path('charge/', charge, name='charge'),    
]

dairy_store/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('accounts/', include('users.urls')),
    path('products/', include('products.urls')),
    path('favorites/', include('user_favorites.urls')),
    path('reviews/', include('reviews.urls')),
    path('orders/', include('orders.urls')),
    path('', include('cart.urls')),
    path('', include('pages.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path

from .views import OrderListView, OrderDetailView

urlpatterns = [
    path('details/<int:pk>/', OrderDetailView.as_view(), name='order_detail'),
    path('', OrderListView.as_view(), name='orders'),
]

orders/models.py
from django.contrib.auth import get_user_model
from django.db import models

from users.models import UserAddress
from products.models import GeneralProduct

# Create your models here.
class Order(models.Model):
    ORDER_STATUS = [
        (1, 'In queue'),
        (2, 'Approved'),
        (3, 'Preparing your order'),
        (4, 'Delivering to customer'),
        (5, 'Delivered')
    ]

    user = models.ForeignKey(get_user_model(), on_delete=models.PROTECT)
    order_date = models.DateTimeField(auto_now_add=True)
    net_sale_amount = models.DecimalField(max_digits=10, decimal_places=2)
    shipping_amount = models.DecimalField(max_digits=10, decimal_places=2)
    total_paid = models.DecimalField(max_digits=10, decimal_places=2)
    destination_address = models.ForeignKey(
        UserAddress, on_delete=models.SET_NULL, null=True, blank=True)
    order_status = models.IntegerField(choices=ORDER_STATUS, default=1)

    def __str__(self):
        return str(self.pk)
    

class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    product = models.ForeignKey(GeneralProduct, on_delete=models.PROTECT)
    count = models.PositiveIntegerField(default=1)
    unit_price = models.DecimalField(max_digits=10, decimal_places=2)
    total_price = models.DecimalField(max_digits=10, decimal_places=2)

    def save(self, *args, **kwargs):
        self.total_price = self.unit_price * self.count
        super(OrderItem, self).save(*args, **kwargs)

    def __str__(self):
        return str(self.pk)

orders/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView
from django.contrib.auth.mixins import LoginRequiredMixin

from .models import Order, OrderItem

class OrderListView(LoginRequiredMixin, ListView):
    model = Order
    template_name = 'orders/user_orders.html'
    context_object_name = 'orders'
    login_url = 'account_login'

    def get_queryset(self, **kwargs):
        return Order.objects.filter(user=self.request.user)


class OrderDetailView(LoginRequiredMixin, DetailView):
    model = Order
    template_name = 'orders/order_details.html'
    context_object_name = 'order'
    login_url = 'account_login'

    def get_context_data(self, **kwargs):
        order_id = self.kwargs['pk']
        context = super().get_context_data(**kwargs)
        itms = OrderItem.objects.filter(order=order_id)
        context["items"] = itms
        return context
    

templates/orders/order_details.html
{% extends '_base_profile.html' %}
{% block title %}order detail{% endblock title %}

{% block profile_content %}
  <div class="container">
    <div class="row">
      <div class="col">
        <div class="card">
          <div class="card-header">
              Order Details
          </div>
          <div class="card-body">
            <table class="table borderless">
              <tbody>
                <tr>
                  <td>Order Status</td>
                  <td><p class="font-weight-bold">{{ order.get_order_status_display }}</p></td>
                  <td>Order Date</td>
                  <td><p class="font-weight-bold">{{ order.order_date }}</p></td>
                </tr>
                <tr>
                  <td>Address
                  </td>
                  <td>
                    <p class="font-weight-bold">{{ order.destination_address.city }},<br>
                       {{ order.destination_address.adress }}</p>
                  </td>
                </tr>
                <tr>
                  <td>Shopping Amount</td>
                  <td><p class="font-weight-bold">{{ order.net_sale_amount }}$</p></td>
                </tr>
                <tr>
                  <td>Shipping Amount</td>
                  <td><p class="font-weight-bold">{{ order.shipping_amount }}$</p></td>
                </tr>
              </tbody>
            </table>
            <hr>
            <h5 style="display:inline">Total Paid: </h5>
            <h5 class="text-danger" style="display:inline">{{ order.total_paid }}</h5>
            <h9 class="text-danger" style="display:inline">$</h9>
          </div>
        </div>
      </div>
    </div>
    <br>
    {% for itm in items %}
      <div class="row">
        <div class="col">
          <div class="card">
            <div class="card-header">
              <a class="text-decoration-none text-dark streched-link" href="{% url 'product_detail' itm.product.pk %}">{{ itm.product.product_name}}</a>
            </div>
            <div class="card-horizontal">
              <div class="img-square-wrapper">
                <img class="product-in-cart" src="{{ itm.product.product_img1.url }}">
              </div>
              <div class="card-body">
                <p>
                  <h5 style="display:inline">Price per unit: </h5>
                  <h5 class="text-danger" style="display:inline">{{ itm.product.price_per_unit }}</h5>
                  <h9 class="text-danger" style="display:inline">$</h9>
                </p>
                <p>
                  <h5 style="display:inline">Count:</h5>
                  <h5 class="text-danger" style="display:inline">{{ itm.count }}</h5>
                </p>
                <p>
                  <h5 style="display:inline">Total: </h5>
                  <h5 class="text-danger" style="display:inline">{{ itm.total_price }}</h5>
                  <h9 class="text-danger" style="display:inline">$</h9>
                </p>
              </div>
            </div>
          </div>
        </div>
      </div>
      <br>
    {% endfor %}
  </div>
{% endblock profile_content %}

templates/orders/shipping_info.html
{% extends '_base.html' %}

{% block title %}Shipping Info{% endblock title %}

{% block content %}
  <div class="container">
    <div class="row">
      <div class="col">
        <div class="card">
          <div class="card-body">
            <h5>SubTotal</h5>
            <hr>
            <p style="display:inline">
                {{ sum_total }} PKR
            </p>
            <hr>
            <h5>Shipping To</h5>
            <p>{{ ship_address.city }}</p>
            <hr>
            <h5>Shipping Cost</h5>
            <p>
              {% if ship_cost >= 0 %}
                {{ ship_cost }} PKR
              {% else %}
                -
              {% endif %}
            </p>
            <hr>
            <h3>Total</h3>
            <h1 class="text-danger" style="display:inline">{{ must_pay }}</h1>
            <h6 class="text-danger" style="display:inline">PKR</h6>
            <br><br>
            <form action="{% url 'charge' %}" method="post">
              {% csrf_token %}
              <script src="https://checkout.stripe.com/checkout.js"
              data-key={{ stripe_key }} data-amount="{{ stripe_amount }}" class="stripe-button" data-locale="auto">
              </script>
            </form>
          </div>
        </div>
        <br>
      </div>
      <div class="col-8">
        <div class="container">
          <div class="row">
            <div class="col">
              <div class="card">
                <div class="card-body">
                  <h5>Choose Shipping Address, Or <a class="text-decoration-none" href="{% url 'add_new_address' %}">add a new address</a></h5>
                  <p>
                    <form method="get" action="">
                      {% csrf_token %}
                      <div class="form-group">
                        <select name="selected_address" class="form-control" onChange="form.submit();">
                          {% if ship_address %}
                            <option value="" hidden>{{ ship_address.adress }}</option>
                          {% else %}
                            <option value="" hidden>Choose An Address</option>
                          {% endif %}
                          {% for address in addresses %}
                            <option value="{{ address.pk }}">{{ address.adress }}</option>
                          {% endfor %}
                        </select>
                      </div>
                      {% if ship_address %}
                        <p>City: {{ ship_address.city }}</p>
                        <p>Address: {{ ship_address.adress|linebreaks }}</p>
                        <p>Zip Code: {{ ship_address.zip_code }}</p>
                      {% endif %}
                    </form>
                  </p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

templates/orders/success_purchase.html
{% extends '_base.html' %}
{% load static %}

{% block title %}
successfull purchase
{% endblock title %}

{% block content %}
<div class="container">
  <div class="row">
    <div class="col">
        <img class="rounded mx-auto d-block" src="{% static 'images/food_truck1.png' %}"></img>
    </div>
  </div>
  <div class="row">
    <div class="col">
      <h3 align="center">Thanks for your shopping!</h3>
      <h3 align="center">Your order will be posted as soon as possible</h3>
    </div>
  </div>
</div>
{% endblock content %}

templates/orders/user_orders.html
{% extends '_base_profile.html' %}

{% block title %}Orders{% endblock title %}

{% block profile_content %}
  <h5>Orders</h5>
  <br><br>
  {% if not orders %}
    <h5 class="text-muted text-center">No Orders yet</h5>
  {% endif %}
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Order Id</th>
        <th>order Date</th>
        <th>Amount Paid</th>
        <th>Status</th>
        <th>Details</th>
      </tr>
    </thead>
    <tbody>
      {% for order in orders %}
        <tr>
          <td>{{ order.pk }}</td>
          <td>{{ order.order_date }}</td>
          <td>{{ order.total_paid }}</td>
          <td>{{ order.get_order_status_display }}</td>
          <td><h3><a class="text-decoration-none text-secondary" href="{% url 'order_detail' order.pk %}"> ></a></h3></td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock profile_content %}

templates/orders/view_cart.html
{% extends '_base.html' %}
{% load static %}

{% block title %}View Cart{% endblock title %}

{% block content %}
  <div class="container">
    <div class="row">
      <div class="col">
        <div class="card">
          <div class="card-body">
            <h5>Total</h5>
            <hr>
            <h1 class="text-danger" style="display:inline">
              {% if items %}
                {{ sum_total }}
              {% else %}
                0
              {% endif %}
            </h1>
            <h6 class="text-danger" style="display:inline"> PKR</h6>
            <hr>
            <a href="{% url 'shipping_info' %}" class="btn btn-success btn-block">Proceed to CheckOut</a>
          </div>
        </div>
        <br>
      </div>
      <div class="col-8">
        <div class="container">
          {% if not items %}
            <div class="container">
              <div class="row">
                <div class="col text-center">
                  <h2 class="text-muted">Your Cart Is Empty</h2>
                </div>
              </div>
            </div>
          {% endif %}
          {% for item in items %}
            <div class="row">
              <div class="col">
                <div class="card">
                  <div class="card-horizontal">
                    <div class="img-square-wrapper">
                      <img class="product-in-cart" src="{{ item.product.product_img1.url }}">
                    </div>
                    <div class="card-body">
                      <h3>{{ item.product.product_name }}</h3>
                      <h5 class="text-danger">{{ item.product.price_per_unit }} PKR
                      </h5>
                      <p>
                        <div class="form-group">
                          <form method="post" action="{% url 'add_item_to_cart' item.product.pk %}">
                            {% csrf_token %}
                            <select name="quantity" class="form-control" onChange="form.submit();">
                              <option value="" hidden>{{ item.quantity }}</option>
                              <option>1</option>
                              <option>2</option>
                              <option>3</option>
                              <option>4</option>
                              <option>5</option>
                            </select>
                          </form>
                        </div>
                      </p>
                      <p>
                        <form method="post" action="{% url 'remove_item_from_cart' item.product.pk %}">
                          {% csrf_token %}
                          <button class="btn btn-danger" type="submit">Delete</button>
                        </form>
                      </p>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <br>
          {% endfor %}
        </div>
      </div>
    </div>
  </div>
{% endblock content %}